# Generated by Django 3.1.1 on 2020-10-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha_fin',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
    ]
