# Generated by Django 3.1.1 on 2020-10-13 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_auto_20201013_0432'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlumnoCategoria',
            new_name='CategoriaAlumno',
        ),
    ]
