# Generated by Django 3.1.1 on 2020-10-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_auto_20201013_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='graduado_fecha',
            field=models.DateField(blank=True),
        ),
    ]
