# Generated by Django 3.1.1 on 2020-10-14 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_auto_20201014_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='v1.persona'),
        ),
    ]
