# Generated by Django 3.1.1 on 2020-10-18 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0008_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='clave_ceneval',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='sede',
            name='extension',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sede',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='sede',
            name='portal_web',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
