# Generated by Django 3.1.1 on 2020-10-27 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0010_auto_20201025_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaalumno',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoriaalumno',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='categoriaalumno',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
