# Generated by Django 3.1.1 on 2020-10-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0012_auto_20201028_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='correo_electronico',
            field=models.EmailField(max_length=254),
        ),
    ]
