# Generated by Django 3.1.1 on 2020-10-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0013_auto_20201028_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaalumno',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='lengua',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='personalengua',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
