# Generated by Django 3.1.1 on 2020-11-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0015_auto_20201030_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('clave', models.CharField(max_length=5)),
                ('clave_dgp', models.CharField(max_length=6)),
                ('clave_ceneval', models.CharField(blank=True, max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=30)),
                ('periodicidad', models.CharField(default='SEMESTRAL', max_length=30)),
                ('vigencia', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('cct', models.TextField()),
                ('nombre', models.TextField()),
                ('acronimo', models.TextField()),
                ('plantel', models.PositiveSmallIntegerField()),
                ('is_num', models.BooleanField(default=False)),
                ('nivel', models.TextField()),
                ('tipo', models.TextField()),
                ('grado', models.TextField()),
                ('sector', models.BooleanField(default=True)),
                ('municipio', models.TextField()),
                ('entidad', models.TextField(default='CHIAPAS')),
                ('pais', models.TextField(default='MÉXICO')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
