# Generated by Django 3.1.1 on 2020-11-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0016_carrera_escuela'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('is_depto', models.BooleanField(default=True)),
                ('parent', models.PositiveIntegerField(null=True)),
                ('superior_at', models.PositiveIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
