# Generated by Django 3.1.1 on 2020-11-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0017_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
