# Generated by Django 3.1.1 on 2020-11-01 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0018_modalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='v1.division'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrera',
            name='modalidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_NULL, related_name='carreras', to='v1.modalidad'),
            preserve_default=False,
        ),
    ]
