# Generated by Django 3.1.1 on 2020-11-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0019_auto_20201101_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalengua',
            name='listening',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='personalengua',
            name='read',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='personalengua',
            name='speeking',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='personalengua',
            name='written',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
