# Generated by Django 3.1.1 on 2020-11-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0020_auto_20201102_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='periodicidad',
            field=models.CharField(blank=True, default='SEMESTRAL', max_length=30),
        ),
    ]
