# Generated by Django 3.1.1 on 2020-11-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0021_auto_20201103_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuela',
            name='acronimo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='cct',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='entidad',
            field=models.CharField(blank=True, default='CHIAPAS', max_length=255),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='grado',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='municipio',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='nivel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='pais',
            field=models.CharField(blank=True, default='MÉXICO', max_length=255),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='plantel',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='tipo',
            field=models.CharField(max_length=255),
        ),
    ]
