# Generated by Django 3.1.1 on 2020-11-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0022_auto_20201106_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalengua',
            old_name='speeking',
            new_name='speaking',
        ),
        migrations.AlterField(
            model_name='lengua',
            name='agrupacion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lengua',
            name='alias',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lengua',
            name='familia',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lengua',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personalengua',
            name='comentarios',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
