# Generated by Django 3.1.1 on 2020-11-06 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0023_auto_20201106_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='v1.modalidad'),
        ),
    ]
