# Generated by Django 3.1.1 on 2020-11-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0024_auto_20201106_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('clave', models.CharField(max_length=6, unique=True)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
