# Generated by Django 3.1.1 on 2020-11-06 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0025_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v1.persona')),
                ('docente', models.IntegerField(default=0)),
                ('grado_nivel', models.CharField(blank=True, max_length=30)),
                ('grado_academico', models.CharField(blank=True, max_length=50)),
                ('grado_estatus', models.CharField(blank=True, max_length=20)),
                ('grado_firma', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('v1.persona',),
        ),
        migrations.CreateModel(
            name='CategoriaEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('promocion', models.DateField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.categoria')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.empleado')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
