# Generated by Django 3.1.1 on 2020-11-07 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0026_categoriaempleado_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('promocion', models.DateField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.division')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.empleado')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
