# Generated by Django 3.1.1 on 2020-11-08 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0028_puesto_puestoempleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='SedeEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('promocion', models.DateField(null=True)),
                ('comentarios', models.TextField(null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.empleado')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.sede')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
